### ISSUE TITLE
Bugs to fix for the JMAG tool for translation

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-native-form#406]
##### Still noticeable bugs on the MLS works
**All widgets**
- [ ]  any of the text with the property keys with special characters that are not `_` don't get resolved correctly e,g 

    - `anc_close.step1.delivery_complications.options.Pre-eclampsia.text = Pre-eclampsia`
    -   `anc_close.step1.delivery_complications.options.Perineal_tear_(2nd,_3rd_or_4th_degree).text = Perineal tear (2nd, 3rd or 4th degree)`

e.g
```
{
            "key": "Perineal tear (2nd, 3rd or 4th degree)",
            "text": "{{anc_close.step1.delivery_complications.options.Perineal tear (2nd, 3rd or 4th degree).text}}",
            "value": false,
            "openmrs_choice_id": "165247AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
```
for keys written with spaces can we replace the spaces with underscores e.g for the piece above we could have had something like `{{anc_close.step1.delivery_complications.options.Perineal_tear_2nd_3rd_or_4th_degree.text}}`

-----------------------------------------------------------------------------------------

- [x]  also interpolate the following on the `edit_text` & `native_edit_text`

```
"v_numeric_integer": {  
  "value": "true",  
  "err": "Enter valid cervical dilation in cm"  
},  
    - "v_min": {  
  "value": "0",  
  "err": "Cervical dilation must be greater than or equal to 0"  
},  
    - "v_max": {  
  "value": "10",  
  "err": "Cervical dilation must be equal to or less than 10"  
}
```
--------------------------------------------------------------------------------------

- [x] Translate the `"specify_info"` attribute in native radio buttons

 ``` {  
  "key": "ultrasound_done",  
  "openmrs_entity_parent": "",  
  "openmrs_entity": "concept",  
  "openmrs_entity_id": "159617AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
  "type": "native_radio",  
  "label": "{{anc_profile.step2.ultrasound_done.label}}",  
  "label_info_text": "{{anc_profile.step2.ultrasound_done.label_info_text}}",  
  "label_info_title": "{{anc_profile.step2.ultrasound_done.label_info_title}}",  
  "label_text_style": "bold",  
  "options": [  
 {  "key": "yes",  
  "text": "{{anc_profile.step2.ultrasound_done.options.yes.text}}",  
  "openmrs_entity_parent": "",  
  "openmrs_entity": "concept",  
  "openmrs_entity_id": "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  
  "specify_info": "ultrasound date",  
  "specify_widget": "date_picker",  
  "max_date": "today",  
  "min_date": "today-9m"  
  },  
  {  
  "key": "no",  
  "text": "{{anc_profile.step2.ultrasound_done.options.no.text}}",  
  "openmrs_entity_parent": "",  
  "openmrs_entity": "concept",  
  "openmrs_entity_id": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"  
  }  
 ],  
  "v_required": {  
  "value": true,  
  "err": "{{anc_profile.step2.ultrasound_done.v_required.err}}"  
  }  
}
```
----------------------------------------------------------------------------------------------------------

- [x]  Translate the `uploadButtonText` attribute on the `choose_image` widget
```
{  
  "key": "wom_image",  
  "openmrs_entity_parent": "",  
  "openmrs_entity": "",  
  "openmrs_entity_id": "",  
  "type": "choose_image",  
  "uploadButtonText": "Take a picture of the woman"  
}
```
-------------------------------------------------------------------------------------------------------

- [x]  Translate the `scanButtonText` attribute on the `barcode` widget
```
{  
  "key": "anc_id",  
  "openmrs_entity_parent": "",  
  "openmrs_entity": "person_identifier",  
  "openmrs_entity_id": "ANC_ID",  
  "type": "barcode",  
  "barcode_type": "qrcode",  
  "hint": "{{anc_register.step1.anc_id.hint}}",  
  "value": "0",  
  "scanButtonText": "Scan QR Code",  
  "v_numeric": {  
  "value": "true",  
  "err": "{{anc_register.step1.anc_id.v_numeric.err}}"  
  },  
  "v_required": {  
  "value": "true",  
  "err": "{{anc_register.step1.anc_id.v_required.err}}"  
  }  
}
```

**Comment by vincent-karuri** [comment]
@dubdabasoduba 

I think we'll still need a comprehensive list of all characters we wish to replace with `_`.

For instance, I see some weird options like `+` and `++` which we'd want to preserve. Hence a blanket rule like `replace all non-alphanumeric characters` won't work.

Could you please help with compiling this list based on ANC?

**Comment by cafootitt** [comment]
@dubdabasoduba @vincent-karuri Feedback/QA so far:

### Main register page
- [ ] Quotation marks are being added around the age in years, and around the total number of clients number
- [ ] An additional number (1) is being prepended to all ages. For example, Aq Za should be 10 years old, Test Test should be 22 years old. So there's an additional digit being added there.
- [ ] Where can I find the translations that are found on this main register page? I need to update the translations, as they are not very good right now, but I can't find them in the anc library on transifex. I would have expected them to appear in the generic strings folder: https://www.transifex.com/opensrp/opensrp-client-anc/translate/#fr/strings-xml--master/182818330?q=translated%3Ano
- [ ] The text on the contact buttons has also changed. They are no longer in all caps, and the line spacing is off now. Can this be fixed in Transifex if you point out the string file location to me?

![Screenshot_20200416-185010_WHO ANC](https://user-images.githubusercontent.com/3488986/79490871-742d0f00-8015-11ea-861d-f38824a78569.jpg)

### Client profile page

- [ ] Where can I find the translations that are found on this page? I need to update the translations, as they are not very good right now, but I can't find them in the anc project in Transifex.

![Screenshot_20200416-190521_WHO ANC](https://user-images.githubusercontent.com/3488986/79490979-a2aaea00-8015-11ea-9557-517b8615fa0f.jpg)
![Screenshot_20200416-190526_WHO ANC](https://user-images.githubusercontent.com/3488986/79490982-a3438080-8015-11ea-8263-fbbc4578e4ae.jpg)

### ANC Reg form

- [ ] The two button labels are not translated, and these are not showing up in Transifex
- [ ] The constraint messages are not translated, and these strings are not showing up in Transifex
- [ ] I need to find the string file in Transifex where "Terminé" is translated, as this is not correct. I can't find this in the ANC project in Transifex.

![Screenshot_20200416-190941_WHO ANC](https://user-images.githubusercontent.com/3488986/79491674-b9057580-8016-11ea-9222-65ab8eb42035.jpg)
![Screenshot_20200416-191120_WHO ANC](https://user-images.githubusercontent.com/3488986/79491677-b99e0c00-8016-11ea-980a-691d556a7779.jpg)
![Screenshot_20200416-191645_WHO ANC](https://user-images.githubusercontent.com/3488986/79491850-f538d600-8016-11ea-81d3-ce9f509fad77.jpg)

### Close ANC Record

No issues so far - good job!

### Quick Check

- [ ] What is the discrepancy between the transifex form name here (Vérification Rapide - note the capital "R" on Rapide) vs. what's in the app (lowercase R)? How is this different?
- [ ] Info icon for central cyanosis is not translated, and the string does not show up in Transifex
- [ ] Where can I find the string for the red refer button and the pop up message after hitting the red refer button? I need to change these translations, and I cannot find them on Transifex.

<img width="1378" alt="Screen Shot 2020-04-16 at 7 21 41 PM" src="https://user-images.githubusercontent.com/3488986/79492319-b8b9aa00-8017-11ea-80af-4b862482a869.png">
![Screenshot_20200416-192319_WHO ANC](https://user-images.githubusercontent.com/3488986/79492353-c8d18980-8017-11ea-80e8-b55c8d9ead0e.jpg)
![Screenshot_20200416-192421_WHO ANC](https://user-images.githubusercontent.com/3488986/79492484-f9b1be80-8017-11ea-99d1-afe54247c0a2.jpg)
![Screenshot_20200416-192541_WHO ANC](https://user-images.githubusercontent.com/3488986/79492658-32ea2e80-8018-11ea-91d8-c86008de7002.jpg)

### Main Contact Container Page

- [ ] Where can I find these translations on Transifex? I need to update them, and I cannot find them
- [ ] The complete check mark is not working on the French version. On this screenshot, the Quick Check should have the Complete check mark here, but it's absent.

![Screenshot_20200416-192759_WHO ANC](https://user-images.githubusercontent.com/3488986/79492898-970cf280-8018-11ea-8287-1d42454fbba5.jpg)

### Exit widget

- [ ] Where can I find these translations on Transifex? I need to update them, and I cannot find them
![Screenshot_20200416-193001_WHO ANC](https://user-images.githubusercontent.com/3488986/79493033-cc194500-8018-11ea-8b83-9545dab0892a.jpg)


### Tests

- [ ] I was unable to check HIV test, as it wasn't showing up when it should have been. We need to look into this. I think it's because some of the pop characteristics have disappeared (will create separate issue for this).
- [ ] The Done today, done earlier, ordered, not done options are not translated for any of the tests; nor are the strings showing up in Transifex

![Screenshot_20200416-194917_WHO ANC](https://user-images.githubusercontent.com/3488986/79494792-7e520c00-801b-11ea-82f8-ca56939d438e.jpg)

**Comment by dubdabasoduba** [comment]
@cafootitt the other translations _(that are native forms & YAML files)_ should be on the `strings.xml` file on transifex.  
@vincent-karuri the validation errors, the two buttons i.e the image & barcode buttons are listed at the top of the issues description. The only new addition it the radio button which shows the `Done Today` options as shown in the screenshot above. I have attached a sample of the same.  Its type is an `extended_radio_button` which is an extension of the `native_radio_button`
```
 {
      "key": "hepb_test_status",
      "openmrs_entity_parent": "161475AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "163725AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "label": "{{tests_hepatitis_b_sub_form.step1.hepb_test_status.label}}",
      "label_text_style": "bold",
      "text_color": "#000000",
      "type": "extended_radio_button",
      "options": [
        {
          "key": "done_today",
          "text": "Done today",
          "type": "done_today",
          "openmrs_entity_parent": "",
          "openmrs_entity": "concept",
          "openmrs_entity_id": "165383AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        },
        {
          "key": "done_earlier",
          "text": "Done earlier",
          "type": "done_earlier",
          "openmrs_entity_parent": "",
          "openmrs_entity": "concept",
          "openmrs_entity_id": "165385AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        },
        {
          "key": "ordered",
          "text": "Ordered",
          "type": "ordered",
          "openmrs_entity_parent": "",
          "openmrs_entity": "concept",
          "openmrs_entity_id": "165384AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        },
        {
          "key": "not_done",
          "text": "Not done",
          "type": "not_done",
          "openmrs_entity_parent": "",
          "openmrs_entity": "concept",
          "openmrs_entity_id": "1118AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        }
      ],
      "v_required": {
        "value": true,
        "err": "{{tests_hepatitis_b_sub_form.step1.hepb_test_status.v_required.err}}"
      }
    }
```

**Comment by cafootitt** [comment]
Hi @dubdabasoduba 

Here is the link to the strings.xml on Transifex: https://www.transifex.com/opensrp/opensrp-client-anc/translate/#fr/strings-xml--master/182818330

As you can see, there are only 2 translations done in this folder. Specifically, things like age and GA are not translated yet, yet they appear translated in the app:

<img width="710" alt="Screen Shot 2020-04-17 at 9 32 05 AM" src="https://user-images.githubusercontent.com/3488986/79549183-8e570380-808e-11ea-869a-c07b28c431b6.png">

Can you look into this further please?

**Comment by dubdabasoduba** [comment]
This [PR](https://github.com/OpenSRP/opensrp-client-anc/pull/330) shows that they were merged from transifex some time back. I can try find out why they don't appear on transifex but I am not sure why that would happen.

**Comment by cafootitt** [comment]
@dubdabasoduba Thanks for helping me figure this out. This seems to be due to the "suggestions" feature in Transifex, so Transifex is using the suggested string from another repo in the absence of an inputted string.

**Comment by vincent-karuri** [comment]
```
@vincent-karuri the validation errors, the two buttons i.e the image & barcode buttons are listed at the top of the issues description. The only new addition it the radio button which shows the Done
```

Thanks @dubdabasoduba, will add the fixes.

**Comment by vincent-karuri** [comment]
@dubdabasoduba I recommend renaming the problematic keys in the ANC app rather than adding rules in JMAG that are not easily generalizable.
